### ISSUE TITLE
More precise exchange rate

### ISSUE THREAD

**Issue by dan-leech** [noojee/money.dart#28]
I'm just curious how to calculate exchanges with better precision.
Google provides courses with 5 digits after the point instead one.

Do I understand correct that I should use 5 instead 2 for all currencies and use pattern with fixed 2 digits?
`Currency.create('USD', 5, pattern='SCCC 0.00')`

**Comment by bsutton** [comment]
That's a really good question and one for which I don't have a pat answer.

So you are going to have to do some experimentation.

I'm currently working through some bugs where the format precision doesn't
match the currency precision so that may cause you aome issues.

My thoughts are that you should try using two USD currencies. One for the
exchange rate with the required precision of 5 and a formatter with a
precision of 5 and one for the result with a precision of 2 and formatter
of precision 2.


Try that and let me know how you go.
